test: subtitle using scroll event
somangoi/okay-to-bleed pull request #8
Opened 2022-08-22 13:36 UTC by Jay-JYKim91

**Why this PR was needed**
- 바닐라 자바스크립트_스크롤 이벤트 이용하여 자막 구현 테스트

**What this PR does**
- src/subtitle/subtitles.json 파일 생성
- 스크롤 이벤트를 이용한 자막 구현

**Outcomes of merging this PR**
- 스크롤 위치에 따라 변경된 자막을 확인할 수 있음

**How urgent is this PR**
- Kinda urgent

**Need to improve**
제가 이번 주중에 작업을 할 수 있을지 확실하지 않아 일단 여기까지 하고 PR 남깁니다.
자막 작업하시게 되면 아래 내용 확인 부탁드립니다🙇‍♀️
- 모바일/데스크탑에 따라 자막 타이밍이 달라져야 함
- throttle 등을 이용하여 스크롤 이벤트 최적화 작업이 필요함_현재는 매우 삐걱댐.

2022-08-24 02:09 UTC, ette9844 approved these changes
확인했습니다.

2022-08-27 15:38 UTC, somangoi commented
주연님 혹시 base branch를 test에서 develop으로 바꿔주실 수 있으신가요~?

2022-08-27 15:41 UTC, somangoi requested changes

2022-08-27 15:41 UTC, somangoi commented on src/components/Subtitle_IntersectionObserver.tsx
> +    console.log(offsetY);
console.log 삭제 부탁드립니다!

2022-08-27 15:41 UTC, somangoi commented on src/components/Subtitle_IntersectionObserver.tsx
> +  const [currentSubtitle, setCurrentSubtitle] = useState('');
혹시 state에 type지정 안해도 오류 안나나요?

2022-08-28 00:39 UTC, Jay-JYKim91 commented
소미님 말씀하신 수정사항 반영하여 푸쉬 해놨습니다~

2022-08-28 00:58 UTC, somangoi approved these changes

2022-08-28 00:58 UTC, merged